### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by neinnew** [klyte45/BuildingColorExpander#3]
[output_log.txt](https://github.com/klyte45/AssetColorExpander/files/6606024/output_log.txt)

The simulation stops and object reference error appear
Everything was fine until at least June 1st.

```
211,478ms | ACEv2 Trying to access controller while loading. NOT ALLOWED!
Ask at Klyte45's GitHub to fix this. Stacktrace:
   at System.Environment.get_StackTrace()
   at Klyte.Commons.Interfaces.BasicIUserModSimplified`2[[Klyte.AssetColorExpander.AssetColorExpanderMod, AssetColorExpander, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null],[Klyte.AssetColorExpander.ACEController, AssetColorExpander, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Controller()
   at Klyte.AssetColorExpander.ACECitizenOverrides.AfterReleaseCitizenInstance(UInt16 instance)
   at CitizenManager.CitizenManager.ReleaseCitizenInstance_Patch1(.CitizenManager , UInt16 )
   at HumanAI.PathfindFailure(UInt16 instanceID, CitizenInstance ByRef data)
   at HumanAI.SimulationStep(UInt16 instanceID, CitizenInstance ByRef data, Vector3 physicsLodRefPos)
   at CitizenManager.SimulationStepImpl(Int32 subStep)
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at CitizenManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at SimulationManager.Managers_LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at LoadingManager+<LoadSimulationData>c__IteratorB.MoveNext()
   at AsyncTask.Execute()
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

211,479ms | Simulation error: Object reference not set to an instance of an object
at Klyte.AssetColorExpander.ACECitizenOverrides.AfterReleaseCitizenInstance (uint16) <0x0002a>
at (wrapper dynamic-method) CitizenManager.CitizenManager.ReleaseCitizenInstance_Patch1 (CitizenManager,uint16) <0x0005d>
at HumanAI.PathfindFailure (uint16,CitizenInstance&) <0x002f5>
at HumanAI.SimulationStep (uint16,CitizenInstance&,UnityEngine.Vector3) <0x00282>
at CitizenManager.SimulationStepImpl (int) <0x0047b>
at SimulationManagerBase`2.SimulationStep (int) <0x0004c>
at CitizenManager.ISimulationManager.SimulationStep (int) <0x00024>
at SimulationManager.LateUpdateData (SimulationManager/UpdateMode,single,single) <0x0017d>
at SimulationManager.Managers_LateUpdateData (SimulationManager/UpdateMode,single,single) <0x000c5>
at LoadingManager/<LoadSimulationData>c__IteratorB.MoveNext () <0x00b99>
at AsyncTask.Execute () <0x000a8>
  [Core]
```

**Comment by illyrius666** [comment]
i got the same error mentioned above.

**Comment by neinnew** [comment]
The strange thing is that an error appears even when only this mod is enabled. so it doesn't seem like a mod conflict, but are all 1000 subscribers going well?

**Comment by GrimGadget** [comment]
I got this error when starting a new game on a clean map.  I'm guessing the map has a plane travelling through from the very beginning.

Latest version of ACE.  I added it to my setup for the first time today.

---
An exception occured during VehicleAI simulation step.
Asset: Aircraft Passenger
VehicleID: 13044
Type: PassengerPlaneAI
Severity: High

System.NullReferenceException: Object reference not set to an instance of an object
at Klyte.AssetColorExpander.ACEVehicleOverrides.get_ColorCache () <0x00022>
at Klyte.AssetColorExpander.ACEVehicleOverrides.AfterReleaseVehicle (uint16) <0x0001c>
at (wrapper dynamic-method) VehicleManager.VehicleManager.ReleaseVehicle_Patch1 (VehicleManager,uint16) <0x0005d>
at AircraftAI.SimulationStep (uint16,Vehicle+,UnityEngine.Vector3) <0x0036f>
at HealkitMod.Patches.VehicleManagerPatch.SimulationStep (VehicleAI,uint16,Vehicle+,UnityEngine.Vector3) <0x00062>
